idle-ws/config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, path: 'admindir', controllers: { sessions: "admindir/v1/admins/sessions" }
  devise_for :users, path: 'v1', controllers: { registrations: "api/v1/registrations", sessions: "api/v1/sesions"}

  namespace :api, path: '' do
    namespace :v1 do
      devise_scope :user do
        post 'register'                                               => 'registrations#create'
        post 'sign-in'                                                => 'sessions#create'
        post 'social'                                                 => 'sessions#social'
      end

      post 'confirm'                                                  => 'users#confirmation'
      post 'stripe'                                                   => 'users#stripe'
      post 'forgot'                                                   => 'users#forgot'
      post 'resend'                                                   => 'users#resend_code'
      post 'stripe/api'                                               => 'users#stripe_api_key'
      get  'stripe/link'                                              => 'users#stripe_url'

      resources :tasks, except: [:new, :create, :edit, :update, :destroy] do
        resources :ignores, only: [:create]
        resources :bids, only: [:create]
        resources :reports, only: [:create]
      end

      resources :users, path: :accounts, except: [:create, :update, :new, :edit, :show, :destroy, :index] do
        collection{
          put 'location'
          put 'status'
          put 'role'
          post 'password'
          post 'stripe/disconnect'                                    => 'users#disconnect'
          put 'cancel'
          put 'read'
          put 'feedback'

          resources :tasks, only: [:create, :update, :destroy] do
            collection{
              get 'progress'
              get 'history'
              get 'directory'
            }
            resources :bids, only: [:index, :destroy]
            put 'completed'
            put 'finished'
            put 'ratings'
            put 'cancel'
          end

          resources :bids, only: [:index] do
            put 'accept'
            put 'cancel'
          end

          resources :conversations, only: [:index] do
            resources :messages, only: [:index]
          end
        }
      end

      resources :users, only: [:show, :update] do
        resources :reports, only: [:create]
        resources :messages, only: [:create]
        get 'completed'
      end
    end
  end

  namespace :admindir do
    namespace :v1, path: '' do
      resources :users, only: [:index, :show, :destroy]
      resources :tasks, only: [:index, :show]
      resources :admins, only: [:index, :edit, :show, :update, :create, :new]
      resources :reports, only: [:index]
      get 'dashboard'                                                 => 'pages#dashboard'
      get 'login'                                                     => 'pages#login'
    end
  end

  get 'mobile/password'                                               => 'pages#password'
  get 'mobile/stripe'                                                 => 'pages#stripe'
  get 'privacy'                                                       => 'pages#privacy'
  get 'contact'                                                       => 'pages#contact'
  post 'feedback'                                                     => 'pages#feedback'
  root to: 'pages#home'
end

idle-ws/app/views/layouts/admin.html.haml
!!!
%html{lang: "en"}
  %head
    %title= yield(:title)
    = stylesheet_link_tag "admin", media: :all

    = javascript_include_tag "admin"

    = yield(:head)

    = csrf_meta_tags

    %meta{content: "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0", name: :viewport}
    %meta{content: "width=device-width", name: :viewport }

    %link{href: "https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css", rel: "stylesheet"}/
    %link{href: "https://fonts.googleapis.com/css?family=Roboto:400,700,300", rel: "stylesheet", type: "text/css"}/

  %body
    - if admin_signed_in?
      .wrapper
        = render partial: "admindir/v1/partials/sidebar"
        .main-panel
          = render partial: "admindir/v1/partials/navigation_bar"
          = yield
    - else
      = yield

    = javascript_include_tag controller_name if File.exists?("#{Rails.root}/app/assets/javascripts/#{controller_name}.js")
    = javascript_include_action_specific_js

  = javascript_include_tag "jquery-ui.min", media: :all
  = javascript_include_tag "bootstrap.min", media: :all

  = yield(:footer)
  = javascript_include_tag "light-bootstrap-dashboard", media: :all

idle-ws/app/views/layouts/application.html.haml
!!!
%html{lang: "en"}
  %head
    %title= yield(:title)

    %meta{ charset: "utf-8"}/
    %meta{ content: "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{ content: "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0", :name => "viewport"}/
    %meta{ content: "width=device-width", :name => "viewport"}/
    %meta{ content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/

    %meta{ property: "fb:app_id", content: "143905502874268"}
    %meta{ property: "og:url", content: "https://www.theidleapp.com"}
    %meta{ property: "og:type", content: "article" }
    %meta{ property: "og:title", content: "Your friendly neighborhood task Platform"}
    %meta{ property: "og:description", content: "Idle is a hyper-local platform for quick tasks and services. It is unique in that all users have the ability to both post and perform tasks."}
    %meta{ property: "og:image", content: "https://www.theidleapp.com/assets/idle.jpg"}

    = stylesheet_link_tag "application", media: :all
    = stylesheet_link_tag "pages", media: :all
    = javascript_include_tag "application", "data-turbolinks-track" => true

    = yield(:head)

    = csrf_meta_tags

    %link{ href: "", rel: "shortcut icon", type: "image/x-icon"}/
    %link{ href: "https://opensource.keycdn.com/fontawesome/4.6.3/font-awesome.min.css ", rel: "stylesheet"}/
    %link{ href: "https://fonts.googleapis.com/css?family=Roboto:400,700,300", rel: "stylesheet", type: "text/css"}/

  %body
    %section.main-wrapper
      .row{style: 'z-index:11;'}
        .col-lg-9.col-md-5.col-sm-4.col-xs-3
          %h1.home-header
            = link_to 'Idle', root_path
        .div-menu
          .col-lg-3.col-md-7.col-sm-8.col-xs-9
            %a.get-in-touch{href: contact_url, style: 'margin-top:-10px; float:right;'}
              %li Get In Touch
          .col-lg-3.col-md-7.col-sm-8.col-xs-9
            %a.privacy-policy{href: privacy_url, style: 'margin-top:-10px; float:right;'}
              %li Privacy Policy
      = yield
    = javascript_include_tag controller_name if File.exists?("#{Rails.root}/app/assets/javascripts/#{controller_name}.js")
    = javascript_include_action_specific_js

idle-ws/app/views/layouts/mobile.html.haml
!!!
%html{lang: "en"}
  %head
    %title= yield(:title)

    = stylesheet_link_tag "reset", media: :all
    = stylesheet_link_tag "mobile", media: :all
    = javascript_include_tag "mobile"

    %title=yield(:title)
    = yield(:head)

    = csrf_meta_tags

    -# %link{href: "/assets/besocialapp.ico", rel: "shortcut icon", type: "image/x-icon"}/
  %body
    = yield

    = javascript_include_tag controller_name if File.exists?("#{Rails.root}/app/assets/javascripts/#{controller_name}.js")
    = javascript_include_action_specific_js